import type { Metadata } from "next";
import "./globals.css";
import { auth } from "@/auth/auth";
import NextAuthSessionProvider from "@/components/providers/SessionProvider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <NextAuthSessionProvider session={session}>
            {children}
            <Toaster position="top-center" richColors />
          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
